language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
before_script:
  - npm install
  - npm run build
  - psql -c 'create database questioner_test_db;' -U postgres
  - export NODE_ENV=test
  - npm run heroku-test-drop
  - npm run heroku-test-migrate
script:
  - npm test
after_success:
  - npm run coverage