/**
 * Queries used in creating relevant tables
 */

const createQueries = {

  // Users table
  usersTable: `
  CREATE TABLE IF NOT EXISTS
   users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_no VARCHAR(15),
    username VARCHAR(100),
    registered_on TIMESTAMP NOT NULL DEFAULT NOW(),
    is_admin BOOLEAN NOT NULL DEFAULT false
  )`,

  // Meetups table
  meetupsTable: `
  CREATE TABLE IF NOT EXISTS
   meetups(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on TIMESTAMP NOT NULL DEFAULT NOW(),
    location VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    happening_on TIMESTAMP NOT NULL,
    tags VARCHAR[]
  )`,

  // Questions table
  questionsTable: `
  CREATE TABLE IF NOT EXISTS
   questions(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id INT REFERENCES users (id),
    meetup_id INT REFERENCES meetups (id),
    title VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL
  )`,

  // RSVP table
  rsvpTable: `
  CREATE TABLE IF NOT EXISTS
   rsvp(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INT REFERENCES users (id),
    meetup_id INT REFERENCES meetups (id),
    response VARCHAR(255),
    PRIMARY KEY(user_id, meetup_id)
  )`,

  // comments table
  commentsTable: `
  CREATE TABLE IF NOT EXISTS
   comments(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment VARCHAR(255),
    user_id INT REFERENCES users (id),
    question_id INT REFERENCES questions (id)
  )`,

  // votes table
  votesTable: `
  CREATE TABLE IF NOT EXISTS
   votes(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    up BOOLEAN,
    down BOOLEAN,
    user_id INT REFERENCES users (id),
    question_id INT REFERENCES questions (id),
    PRIMARY KEY(user_id, question_id)
  )`,
};


/**
 * Queries used in dropping relevant tables
 */

const dropQueries = {

  // Users table
  usersTable: 'DROP TABLE IF EXISTS users',

  // Meetups table
  meetupsTable: 'DROP TABLE IF EXISTS meetups',

  // Questions table
  questionsTable: 'DROP TABLE IF EXISTS questions',

  // RSVP table
  rsvpTable: 'DROP TABLE IF EXISTS rsvp',

  // Comments table
  commentsTable: 'DROP TABLE IF EXISTS comments',

  // Votes table
  votesTable: 'DROP TABLE IF EXISTS votes',
};

/**
 * Queries used in seeding tables
 */

const seedQueries = {

  // Users table
  usersTable: `
    INSERT INTO users(firstname, lastname, email, password, is_admin)
      VALUES ('chukwudi', 'ume', 'chukwudi.ume@gmail.com', 'andela', true),
              ('Ernest', 'Genius', 'e.genius@gmail.com', 'andela', false),
              ('Chike', 'Bad guy', 'c.guy@gmail.com', 'andela', false)
  `,

  meetupsTable: `
    INSERT INTO meetups(location, topic, happening_on)
      VALUES ('Gbagada', 'NodeJS Gurus', 1547078599932),
              ('The zone, Maryland', 'Food Lovers', 1547878599932),
              ('Maryland Mall', 'Movie Critics', 1547578599932)
  `,

  questionsTable: `
    INSERT INTO questions(user_id, meetup_id, title, body)
      VALUES (1, 2, 'What about', 'Okay. this is not so great. Is it?'),
              (2, 1, 'Transportation', 'Will transport be provided?'),
              (1, 3, 'Item 7', 'Will item 7 be provided?')
  `,

  rsvpTable: `
    INSERT INTO rsvp(user_id, meetup_id, response)
      VALUES (1, 2, 'yes'),
              (1, 1, 'no'),
              (2, 1, 'maybe')
  `,

  commentsTable: `
    INSERT INTO comments(comment, user_id, question_id)
      VALUES ('Beautiful question', 2, 1),
              ('Very thoughful', 1, 2),
              ('This question is a question', 1, 1)
  `,

  votesTable: `
    INSERT INTO votes(up, down, user_id, question_id)
      VALUES (true, ,1,2),
              ('true', ,2,2),
              ( , true, 1, 1)
  `,

};

module.exports = {
  createQueries,
  dropQueries,
  seedQueries,
};
