/**
 * Queries used in creating relevant tables
 */

const createQueries = {

  // Users table
  usersTable: `
  CREATE TABLE IF NOT EXISTS
   users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(15),
    username VARCHAR(100),
    registered TIMESTAMP NOT NULL DEFAULT NOW(),
    isAdmin BOOLEAN NOT NULL DEFAULT false
  )`,

  // Meetups table
  meetupsTable: `
  CREATE TABLE IF NOT EXISTS
   meetups(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdOn TIMESTAMP NOT NULL DEFAULT NOW(),
    location VARCHAR(255),
    topic VARCHAR(255),
    happeningOn TIMESTAMP,
    tags VARCHAR[]
  )`,

  // Questions table
  questionsTable: `
  CREATE TABLE IF NOT EXISTS
   questions(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdOn TIMESTAMP NOT NULL DEFAULT NOW(),
    userID INT REFERENCES users (id),
    meetupID INT REFERENCES meetups (id),
    title VARCHAR(255),
    body VARCHAR(255)
  )`,

  // RSVP table
  rsvpTable: `
  CREATE TABLE IF NOT EXISTS
   rsvp(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userID INT REFERENCES users (id),
    meetupID INT REFERENCES meetups (id),
    response VARCHAR(255),
    PRIMARY KEY(userID, meetupID)
  )`,

  // comments table
  commentsTable: `
  CREATE TABLE IF NOT EXISTS
   comments(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment VARCHAR(255),
    userID INT REFERENCES users (id),
    questionID INT REFERENCES questions (id)
  )`,

  // votes table
  votesTable: `
  CREATE TABLE IF NOT EXISTS
   votes(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    up BOOLEAN,
    down BOOLEAN,
    userID INT REFERENCES users (id),
    questionID INT REFERENCES questions (id),
    PRIMARY KEY(id, userID)
  )`,
};


/**
 * Queries used in dropping relevant tables
 */

const dropQueries = {

  // Users table
  usersTable: 'DROP TABLE IF EXISTS users',

  // Meetups table
  meetupsTable: 'DROP TABLE IF EXISTS meetups',

  // Questions table
  questionsTable: 'DROP TABLE IF EXISTS questions',

  // RSVP table
  rsvpTable: 'DROP TABLE IF EXISTS rsvp',

  // Comments table
  commentsTable: 'DROP TABLE IF EXISTS comments',

  // Votes table
  votesTable: 'DROP TABLE IF EXISTS votes',
};

module.exports = {
  createQueries,
  dropQueries,
};
